#pragma once

#define FINISHED_REQUIERMENTS "abcdefhijlm"

#define SCREEN_WIDTH	640
#define SCREEN_HEIGHT	480

#define STARTING_LIVES 3
#define UNLIMITED_LIVES_PERIOD 10

#define CHARSET_SIZE 8
#define BIGCHARSET_SIZE 16

#define TICK_UPDATE_CAP 20
#define POINT_FOR_DRIVING_INTERVAL 500

#define ROAD_TILE_HEIGHT	500
#define OFF_ROAD_MARIGIN	30
#define TREE_DISTANCE OFF_ROAD_MARIGIN

#define MAX_SPEED				25
#define ACCELERATION			1
#define BREAK_DECELERATION		-1
#define MAX_REVERSE_SPEED		-10
#define REVERSE_ACCELERATION	-0.5
#define REVERSE_DECELERATION	0.3
#define DECELERATION			-0.3

#define TURN_SPEED 0.7
#define UNTURN_SPEED -0.3
#define MAX_TURN_SPEED 7

#define HITBOX_MARIGIN 5
#define ENEMY_AIM_MARIGIN 5
#define OVERTAKING_MARIGIN 0
#define MAX_ENEMY_SPEED 26
#define MAX_NPC_SPEED 15

#define POINTS_FOR_DRIVING 1
#define SCORE_FOR_ENEMY_DESTRUCTION 50
#define LIVE_POINT_COST 100
#define POINT_COOLDOWN_FOR_NPC_DESTRUCTION 5000

#define MAIN_CAR_Y 300
#define MAIN_CAR_X SCREEN_WIDTH/2 + 100

#define CAR_W 30
#define CAR_H 48

#define NPC_AMMOUNT 3
#define ENEMY_AMMOUNT 2

#define CAR_HITBACK 3
#define REDUCED_CAR_HITBACK 0.5

#define RESPAWN_TIME 500
#define MAIN_RESPAWN_TIME 2000

#define BOX_WIDTH 300
#define BOX_HEIGHT 150

#define SPAWN_GAP 50
#define SPAWN_CAR_PER_ROW (int)(SCREEN_WIDTH/2 / SPAWN_GAP)

#define BULLET_WIDTH 10
#define BULLET_HEIGHT 20
#define UPGRADE_BULLET_WIDTH 30
#define UPGRADE_BULLET_HEIGHT 40
#define UPGRADE_ENTITY_SIZE 30

#define BULLET_SPEED 50
#define UPGRADE_AMMO 5
#define MAX_BULLET_COUNT 5

#define SHOOTING_COOLDOWN 500