#pragma once

#define FINISHED_REQUIERMENTS "abcdefh"

#define SCREEN_WIDTH	640
#define SCREEN_HEIGHT	480

#define CHARSET_SIZE 8
#define BIGCHARSET_SIZE 16

#define TICK_UPDATE_CAP 25
#define POINT_FOR_DRIVING_INTERVAL 500

#define ROAD_TILE_HEIGHT	250
#define OFF_ROAD_MARIGIN	70
#define TREE_DISTANCE 100

#define MAX_SPEED				30
#define ACCELERATION			1
#define BREAK_DECELERATION		-0.7
#define MAX_REVERSE_SPEED		-10
#define REVERSE_ACCELERATION	-0.5
#define REVERSE_DECELERATION	0.3
#define DECELERATION			-0.3

#define TURN_SPEED 0.5
#define UNTURN_SPEED -1
#define MAX_TURN_SPEED 7

#define POINTS_FOR_DRIVING 1

#define BOX_WIDTH 300
#define BOX_HEIGHT 150